"""
migrate_db.py
Run ONCE to fix two issues:
1. Old users.db missing 'id' column  → recreates table preserving all users
2. labels.npy missing from root      → copies from correct location if found

Run: python migrate_db.py
"""

import sqlite3
import os
import shutil
import hashlib

DB_PATH = "users.db"

print("=" * 50)
print("  HAR Database Migration Tool")
print("=" * 50)

# ── Fix 1: users.db schema ──────────────────────
print("\n[1] Checking users.db schema...")

conn = sqlite3.connect(DB_PATH)
cur  = conn.execute("PRAGMA table_info(users)")
cols = [row[1] for row in cur.fetchall()]
conn.close()

print(f"    Existing columns: {cols}")

if "id" not in cols:
    print("    'id' column missing — migrating...")
    conn = sqlite3.connect(DB_PATH)

    # Read existing users
    try:
        rows = conn.execute("SELECT username, password FROM users").fetchall()
    except Exception:
        rows = []
    conn.close()

    # Rename old table, create new one, copy data
    conn = sqlite3.connect(DB_PATH)
    conn.execute("ALTER TABLE users RENAME TO users_old")
    conn.execute("""
        CREATE TABLE users (
            id       INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    """)
    for username, password in rows:
        conn.execute("INSERT INTO users (username, password) VALUES (?, ?)",
                     (username, password))
    conn.execute("DROP TABLE users_old")
    conn.commit()
    conn.close()
    print(f"    Migrated {len(rows)} users successfully.")

    # Ensure admin exists
    conn = sqlite3.connect(DB_PATH)
    admin_exists = conn.execute(
        "SELECT 1 FROM users WHERE username='admin'"
    ).fetchone()
    conn.close()
    if not admin_exists:
        conn = sqlite3.connect(DB_PATH)
        pw_hash = hashlib.sha256("admin123".encode()).hexdigest()
        conn.execute("INSERT OR IGNORE INTO users (username, password) VALUES (?, ?)",
                     ("admin", pw_hash))
        conn.commit()
        conn.close()
        print("    Admin user created: admin / admin123")
else:
    print("    Schema OK — no migration needed.")

# ── Fix 2: labels.npy ───────────────────────────
print("\n[2] Checking labels.npy...")
if not os.path.exists("labels.npy"):
    # Search common locations
    candidates = [
        "pose_data/labels.npy",
        "models/labels.npy",
    ]
    found = None
    for c in candidates:
        if os.path.exists(c):
            found = c
            break
    if found:
        shutil.copy(found, "labels.npy")
        print(f"    Copied from {found}")
    else:
        print("    labels.npy not found anywhere.")
        print("    This file is generated by create_dataset.py")
        print("    Run: python create_dataset.py")
else:
    import numpy as np
    y = np.load("labels.npy")
    print(f"    labels.npy OK — {len(y)} samples")

print("\n" + "=" * 50)
print("  Migration complete. Restart Streamlit now.")
print("=" * 50)